name: Update Wordle via Issue

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm ci

      - name: Process guess
        run: node scripts/processGuess.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
